name: DEV - Build

on:
  workflow_dispatch:

  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  APP_NAME: rg-dpu-gitaction-1
  CONTAINER_REPOSITORY: "gitaction.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  unitest:
    name: UnitTest
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
